language: python
matrix:
    include:
        - os: osx
          language: generic
          install: .travis/install.sh
          env:
              - TOXENV=lint,py3,coverage,mypy
os:
    - linux
services:
    - docker
python:
    - "3.6"
env:
    - TOXENV=lint,py3,coverage,mypy
    - TOXENV=itests_simple
    - TOXENV=itests_complex
    - TOXENV=itests_dht
script:
    - tox
