language: python
cache:
  pip: true
  directories:
    - .tox/
before_cache:
  # We don't currently use any secure environment variables, but just in case, and also to avoid caches that grow forever, remove log dirs.
  - rm -rf .tox/*/log .tox/log .tox/*/local/log
  # For some reason (because we build the manpages toxenv inside docker, maybe?), caching .tox/manpages leads to failing itest_% builds.
  - rm -rf .tox/manpages
services:
    - docker
python:
    - "3.6"
env:
    - TOXENV=lint,py3,coverage,mypy,docs,doctest
    - TOXENV=itests_simple
    - TOXENV=itests_complex
    - TOXENV=itests_dht
script:
    - tox
