language: python
cache:
  pip: true
  directories:
    - .tox/
    - $HOME/.cache/pip-faster/
    - $HOME/.cache/pre-commit/
before_cache:
    - rm -rf .tox/*/log .tox/log .tox/*/local/log
    - rm -rf .tox/manpages
services:
    - docker
python:
    - "3.6"
env:
    - TOXENV=lint,py3,coverage,mypy,docs,doctest
    - TOXENV=itests_simple
    - TOXENV=itests_complex
    - TOXENV=itests_dht
install: pip install tox
script:
    - tox
